# .github/workflows/sync-nuclei-zip.yml
on:
  schedule:
    - cron: '0 6 * * 0'  
  workflow_dispatch:       # 也支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub nuclei-templates
        run: git clone --depth 1 https://github.com/projectdiscovery/nuclei-templates

      - name: Create zip (only needed dirs)
        run: |
          cd nuclei-templates
          zip -r nuclei-templates.zip http/ network/ dns/ ssl/ file/ code/

      - name: Push zip to Gitee
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          git clone https://ksaliang:${GITEE_TOKEN}@gitee.com/ksaliang/nuclei-templates.git gitee-repo
          cp nuclei-templates/nuclei-templates.zip gitee-repo/
          cd gitee-repo
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add nuclei-templates.zip
          git diff --cached --quiet || git commit -m "update nuclei-templates.zip" && git push
